site_author: SKT 주재현
site_description: initial Platform
site_url: https://initial-v2-platform.readthedocs.io/
google_analytics: ['UA-171779938-1', 'https://initial-v2-platform.readthedocs.io/']

repo_url: https://github.com/sktston/initial-v2-platform-doc

site_name: initial Platform
nav:
  - 'Initial Platform' :
      - 'Introduction' : 'index.md'
#      - 'Terms' : 'terms.md'
      - 'Services': 'services.md'
#      - 'Release notes' : 'release_note.md'
#      - '이용약관' : 'termsofuse.md'
#      - '오픈소스고지문' : 'initial platform_v1.0_오픈소스고지문_20210325.htm'
      - '오픈소스고지문' : 'opensource.md'
#      - '개인정보수집/이용' : 'privacyuse.md'
#  - 'Mobile Agency Service' :
#      - 'Initial Agency' : 'agency.md'
#      - 'Agency Protocols' : 'agency_protocol.md'
  - 'Web Console Service' :
      - 'Web Console 소개' : 'web_console.md'
      - 'Web Console 이용방법' : 'web_console_signup.md'
      - 'Web Console 개발 Guide': 'web_console_guide.md'
      - 'FAQ': 'web_console_FAQ.md'


  - 'initial DID Agent API Guide':
      - 'Open API list & Method': 'open_api_list.md'
#      - 'Wallet & DID' : 'open_api_wallet.md'
      - 'Connection': 'open_api_auto_connection.md'
      - 'Verify': 'open_api_proof.md'
      - 'Message': 'open_api_message.md'
      - 'Issue': 'open_api_auto_credential.md'
            #      - 'Manual Connection': 'open_api_manual_connection.md'
#      - 'Router Connection': 'open_api_router_connection.md'
      - 'Schema & Credential ID 등록': 'open_api_schema_creddef.md'
#      - 'Manual Credential Issue': 'm_credential.md'
      - 'Revocation': 'open_api_revocation.md'
      - 'initial Deeplink' : 'initial_deeplink.md'
  - 'Reference - Demo Samples' :
#      - 'DID VCX Java Demo' : 'demo.md'
#      - 'DID VCX NodeJS Demo': 'node_demo.md'
      - 'Open API Demo' : 'cloud_agent_demo.md'
      - 'Swagger' : 'https://app.swaggerhub.com/apis-docs/khujin1/initial_Cloud_Agent_Open_API/1.0.4#/'
#  - 'SDK API' :
#      - 'Java APIs' : 'java_api/java_api.md'
#      - 'iOS APIs' : 'ios_api/ios_api.md'
#  - 'Blockchain Node' :
#      - 'Blockchain Network' : 'blockchain.md'


plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  nav_style: light
  navigation_depth : 2
  highlightjs : true
  hljs_style : github

extra:
  version: 2.1.6